"""qas add movie

Revision ID: 032d499105b7
Revises: 14beb2787df2
Create Date: 2025-08-27 13:50:00.728717+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032d499105b7'
down_revision: Union[str, Sequence[str], None] = '14beb2787df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qas_config', sa.Column('movie_save_path_prefix', sa.String(length=256), server_default='/', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qas_config', 'movie_save_path_prefix')
    # ### end Alembic commands ###
