"""emby

Revision ID: 14beb2787df2
Revises: 65706fbf0732
Create Date: 2025-08-16 16:03:46.950000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14beb2787df2'
down_revision: Union[str, Sequence[str], None] = '65706fbf0732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emby_config', sa.Column('username', sa.String(length=256), server_default='admin', nullable=False))
    op.add_column('emby_config', sa.Column('password', sa.String(length=256), server_default='admin', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emby_config', 'password')
    op.drop_column('emby_config', 'username')
    # ### end Alembic commands ###
