"""add qas

Revision ID: 4fb03f4e9a6d
Revises: d5562565aa2c
Create Date: 2025-08-02 04:42:12.855198+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb03f4e9a6d'
down_revision: Union[str, Sequence[str], None] = 'd5562565aa2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qas_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_token', sa.String(length=256), nullable=False),
    sa.Column('save_path_prefix', sa.String(length=256), server_default='/', nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=256), nullable=False),
    sa.Column('pattern', sa.String(length=256), server_default='.*.(mp4|mkv)', nullable=False),
    sa.Column('replace', sa.String(length=256), server_default='{SXX}E{E}.{EXT}', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qas_config')
    # ### end Alembic commands ###
